- name: "Validate composer.json and composer.lock"
  run: "composer validate"

- name: "composer self-update"
  run: "composer self-update"

- name: "Get composer cache directory"
  id: composer-cache
  run: echo "::set-output name=dir::$(composer config cache-files-dir)"

- name: "Cache composer dependencies"
  uses: actions/cache@v2
  with:
    path: "${{ steps.composer-cache.outputs.dir }}"
    key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
    restore-keys: ${{ runner.os }}-composer-

- name: "Install dependencies with Composer"
  run: "composer install --no-interaction --no-progress --prefer-dist"
